server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_service
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active: dev
logging:
  level:
    org.springframework: INFO
    com.dkowalczyk: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info
