server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api_gateway
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active: dev
jwt:
  secret: 'dev_jwt_secret_key'
  expiration: 3600000
logging:
  level:
    org.springframework: DEBUG
    com.dkowalczyk: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
